### ISSUE TITLE
Random CPU Usage

### ISSUE THREAD

**Issue by Kintak** [Saishy/certainmangareader#11]
I love this addon but I must disable it. It's causing Firefox to use CPU while doing nothing at all. I wouldn't be surprised if there's a memory leak in there as well. I just went through all of my addons to figure out which one was eating CPU and this is the one that was causing the issue.
I hope it'll be fixed in the future, although it looks like updates are quite slow since the Batoto loader has been broken for months on my end (skips something like pages 7 and 8 on every chapter). Version 2.3.2 by the way.

**Comment by Saishy** [comment]
What is your OS?

And about the batoto thing that is indeed strange, it's my most used
website to read from and you are the first person to ever complain about
it, could you link me a manga that shows the error?

And if you could export your manga list and send it to me it would greatly
help me!

Yeah, updates are scarce since I'm barely making a living and in the years
since the release of the addon it has only received two donations ever...
