### ISSUE TITLE
Flaky MangaFox Support

### ISSUE THREAD

**Issue by megamit** [Saishy/certainmangareader#17]
Is never able to get through an entire chapter before the images refuse to load.
Im assuming this is mangafox doing some kind of scraping protection.
It would be nice to be able to toggle support for specific sites so i dont have to flick the extension on and off constantly.

**Comment by Saishy** [comment]
The support for specific sites is a nice idea.

I don't know if you updated to the last version, because beta and releases don't update between them. (So if you are on release and a newer beta comes, you don't get it, same for the opposite)

This is not a protection of mangafox, sometimes the site is just shitty, other times they change servers.

Sorry the addon is being updated to webext and will be released soon, but while I'm doing the conversion I'm not able to keep updating this version.
